baseurl = "https://regiszhao.github.io/"
title = "regiszhao"
theme = "smol"
languageCode = "en-us"

# Parameters
[params]
    subtitle = "Currently trying to pass third year."
    dateFmt = "02.01.2006 15:04"

# Header
[menu]
  [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about/"
        weight = 1 

  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 2 

#  [[menu.main]]
#        identifier = "categories"
#        name = "Categories"
#        url = "/categories/"
#        weight = 2 

  [[menu.main]]
        identifier = "notes"
        name = "Notes"
        url = "/notes/"
        weight = 3 

  [[menu.main]]
        identifier = "tags"
        name = "Tags"
        url = "/tags/"
        weight = 4

# Footer
  [[menu.footer]]
        name = "Github"
        url = "https://github.com/example"
        weight = 1 

    [[menu.footer]]
        name = "Mastodon"
        url = "https://example.com/@user"
        weight = 2 

    [[menu.footer]]
        name = "Imprint"
        url = "/imprint"
        weight = 3 
